### ISSUE TITLE
Dotadraft.Setup.0.1.1 issues

### ISSUE THREAD

**Issue by chozandrias76** [dotadraft/dotadraft_ui#1]
![image](https://user-images.githubusercontent.com/2087677/113229470-ea894800-924b-11eb-844d-cae4e14328a0.png)
It would be useful to include your name as I've seen before if you can't get around displaying this warning.

**Comment by chozandrias76** [comment]
Unfortunately I also get a blank screen on this one, even after deleting `C:\Users\swens\AppData\Roaming\dotadraft`

**Comment by chozandrias76** [comment]
![image](https://user-images.githubusercontent.com/2087677/113229919-c7ab6380-924c-11eb-8fd6-6ad7549eb039.png)
```sh
loading data
prewarming
[51756:0331/181231.195:INFO:CONSOLE(40368)] "SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.", source: file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js (40368)
[51756:0331/181231.199:INFO:CONSOLE(33448)] "%cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
You might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq font-weight:bold", source: file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js (33448)
GameStateServer listening at http://127.0.0.1:9990
[51756:0331/181231.284:INFO:CONSOLE(586)] "Uncaught TypeError: Cannot read property 'stats_skills' of undefined", source: file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js (586)
[51756:0331/181231.287:INFO:CONSOLE(27294)] "The above error occurred in the <Context.Consumer> component:

    at Draft (file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js:564:5)
    at Route (file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js:34552:29)
    at Switch (file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js:34758:29)
    at div
    at Router (file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js:34181:30)
    at HashRouter (file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js:33835:35)
    at div
    at App (file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js:1249:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.", source: file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js (27294)
[51756:0331/181231.287:INFO:CONSOLE(30479)] "Uncaught TypeError: Cannot read property 'stats_skills' of undefined", source: file:///C:/Users/swens/AppData/Local/Programs/dotadraft/resources/app.asar/build/js/mainWindow.app.js (30479)
prewarmed in 910 ms

**Comment by saschalippert** [comment]
the issue has been fixed.

thanks for your help
